# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.3

      - name: Build the project
        run: |
          npm i -g yarn
          yarn
          yarn build
      
      # - name: deploy to server
      #   run: |
      #     echo "$SSH_PRIV_KEY" >> ./keyfile 
      #     ssh -i ./keyfile $SSH_USER@stoic-calendar.com su -c '$SCRIPT_PATH'
      #   shell: bash
      #   env:
      #     SSH_PRIV_KEY: ${{secrets.DEPLOY_KEY}}
      #     SSH_USER: ${{ secrets.SERVER_USERNAME }}
      #     SCRIPT_PATH: ${{ secrets.SCRIPT }}
      - name: save private key 
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" >> ./file.key
          chmod 600 ./file.key

      - name: check key
        run: stat ./file.key

      - name: deploy ssh
        uses: appleboy/ssh-action@master
        with:
          host: stoic-calendar.com
          username: ${{ secrets.SERVER_USERNAME }}
          key_path: ./file.key
          script: ${{ secrets.SCRIPT }}